backend/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^bloomers/', views.bloomers, name="bloomers"),
    url(r'^bloomer_details/(?P<username>[0-9A-Za-z]+)/$', views.bloomer_details, name="bloomer_details"),
    url(r'^classrooms/', views.classrooms, name="classrooms"),
    url(r'^classroom_details/(?P<name>[0-9A-Za-z]+)/$', views.classroom_details, name="classroom_details"),
    url(r'^envelopes/', views.envelopes, name='envelopes'),
    url(r'^sendEnvelope/', views.sendEnvelope, name="sendEnvelope"),
    url(r'^series/', views.series, name="series"),
    url(r'^serie_details/(?P<serieSerial>[0-9A-Za-z]+)/$', views.serie_details, name="serie_details"),
    url(r'^serie_new/', views.serie_new, name="serie_new"),
    url(r'^topic_details/(?P<topicSerial>[0-9A-Za-z]+)/$', views.topic_details, name="topic_details"),
    url(r'^topic_new/(?P<serieSerial>[0-9A-Za-z]+)/$', views.topic_new, name="topic_new"),
    url(r'^question_details/(?P<questionSerial>[0-9A-Za-z]+)/$', views.question_details, name="question_details"),
    url(r'^question_new/(?P<topicSerial>[0-9A-Za-z]+)/$', views.question_new, name="question_new"),
    url(r'^option_details/(?P<optionSerial>[0-9A-Za-z]+)/$', views.option_details, name="option_details"),
    url(r'^option_new/(?P<questionSerial>[0-9A-Za-z]+)/$', views.option_new, name="option_new"),
    url(r'^copy/(?P<oldSerial>[0-9A-Za-z]+)-(?P<newSerial>[0-9A-Za-z]+)/$', views.copy, name="copy"),
    url(r'^delete/(?P<serial>[0-9A-Za-z]+)/$', views.delete, name="delete"),
    ###
    url(r'^claim/$', views.claim, name="claim"),
    url(r'^claim_solved/(?P<claim_pk>[0-9A-Za-z]+)/$', views.claim_solved, name="claim_solved"),
    url(r'^claims/$', views.claims, name="claims"),
    url(r'^create_bulk_bool/$', views.create_bulk_bool, name="create_bulk_bool"),
    url(r'^create_multi/$', views.create_multi, name="create_multi"),
    url(r'^create_topic/$', views.create_topic, name="create_topic"),
    url(r'^new_question/', views.new_question, name="new_question"),
    url(r'^pendings/', views.pendings, name="pendings"),
    url(r'^pending_details/(?P<option_pk>[0-9A-Za-z]+)/', views.pending_details, name="pending_details"),
    url(r'^pending_solved/(?P<option_pk>[0-9A-Za-z]+)/', views.pending_solved, name="pending_solved"),
    ###
    #url(r'^topic_questions/(?P<topic_serial>[0-9A-Z]+)/$', views.topic_questions, name="topic_questions"),
    #url(r'^tools/add_questionmultiple/$', views.tools_add_questionmultiple, name="tools_add_questionmultiple"),
]

blooming/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^profile/$', views.profile, name='profile'),
]

look/urls.py
from django.conf.urls import url

from . import views
from back import views as back_views

urlpatterns = [
    url(r'^$', views.main, name="main"),
    url(r'^html/$', views.html, name="html"),
    url(r'^back/$', back_views.back, name="back"),
]

yamath/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blooming.views import index, login_view

urlpatterns = [
    url(r'^$', index, name='main'),
    url(r'^login/$', login_view),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^bloomerprofile/', include('bloomerprofile.urls', namespace='bloomerprofile')),
    url(r'^backend/', include('backend.urls', namespace='backend')),
    url(r'^blooming/', include('blooming.urls', namespace='blooming')),
    url(r'^experimental/', include('look.urls', namespace='look')),
]

blooming/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from random import shuffle


class Bloomer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40, blank=True, null=True)
    last_name = models.CharField(max_length=40, blank=True, null=True)
    email = models.CharField(max_length=40, blank=True, null=True)
    professor = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def _get_classrooms(self):
        return [ cb.classroom for cb in ClassroomBloomer.objects.filter(bloomer=self) ]

    def _get_score_mean(self):
        return sum( self.get_scorevalue_of(t) for t in self.topics )/len(self.topics)

    def _get_topics(self):
        return list({ topic for classroom in self.classrooms for topic in classroom.topics })

    def get_scorevalue_of(self, topic):
        try:
            return Score.objects.get(user=self.user, topic=topic).value
        except:
            return 0

    def add_scorevalue_of(self, topic, i):
        try:
            score = Score.objects.get(user=self.user, topic=topic)
        except:
            score = Score(user=self.user, topic=topic, value=0)
        score.value = min(100, max(0, score.value+i))
        score.save()

    def update_classrooms(self, classrooms_serial_list):
        classrooms_to_add = set(classrooms_serial_list) - set([ c.serial for c in self.classrooms ])
        classrooms_to_delete = set([ c.serial for c in self.classrooms ]) - set(classrooms_serial_list)
        for serial in classrooms_to_add:
            ClassroomBloomer(bloomer=self, classroom=Classroom.objects.get(serial=serial)).save()
        for serial in classrooms_to_delete:
            ClassroomBloomer.objects.get(bloomer=self, classroom=Classroom.objects.get(serial=serial)).delete()


    classrooms = property(_get_classrooms)
    topics = property(_get_topics)
    score_mean = property(_get_score_mean)

class Classroom(models.Model):
    serial = models.CharField(max_length=4, unique=True)

    def __str__(self):
        return self.serial

    def _get_bloomers(self):
        return [ cb.bloomer for cb in ClassroomBloomer.objects.filter(classroom=self) ]

    def _get_topics(self):
        return list({ tc.topic for tc in TopicClassroom.objects.filter(classroom=self) })

    def add_bloomer(self, bloomer):
        if bloomer not in self.bloomers:
            ClassroomBloomer(bloomer=bloomer, classroom=self).save()

    def delete_bloomer(self, bloomer):
        if bloomer in self.bloomers:
            ClassroomBloomer.objects.get(bloomer=bloomer, classroom=self).delete()

    def add_topic(self, topic):
        if topic not in self.topics:
            TopicClassroom(topic=topic, classroom=self).save()

    def delete_topic(self, topic):
        if topic in self.topics:
            TopicClassroom.objects.get(topic=topic, classroom=self).delete()

    bloomers = property(_get_bloomers)
    topics = property(_get_topics)

class ClassroomBloomer(models.Model):
    bloomer = models.ForeignKey(Bloomer, related_name="classroombloomer_bloomer")
    classroom = models.ForeignKey(Classroom, related_name="classroombloomer_classroom")

    def __str__(self):
        return "%s in %s" % (self.bloomer, self.classroom)

class Topic(models.Model):
    text = models.CharField(max_length=80)
    bloom_index = models.IntegerField(  blank=True, null=True,
                                        choices=(   (1, 'remembering'),
                                                    (2, 'understanding'),
                                                    (3, 'applying'),
                                                    (4, 'analyzing'),
                                                    (5, 'evaluating'),
                                                    (6, 'creating'), ))
    mobile = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def update_antes(self, antes_pk_list):
        for pk in antes_pk_list:
            try:
                t = Topic.objects.get(pk=int(pk))
                if t not in self.antes:
                    TopicDependency(ante=t, post=self).save()
            except:
                pass
        for t in self.antes:
            if str(t.pk) not in antes_pk_list:
                TopicDependency.objects.get(ante=t, post=self).delete()

    def update_posts(self, posts_pk_list):
        for pk in posts_pk_list:
            try:
                t = Topic.objects.get(pk=int(pk))
                if t not in self.posts:
                    TopicDependency(ante=self, post=t).save()
            except:
                pass
        for t in self.posts:
            if str(t.pk) not in posts_pk_list:
                TopicDependency.objects.get(ante=self, post=t).delete()

    def update_classrooms(self, classrooms_serial_list):
        classrooms_to_add = set(classrooms_serial_list) - set([ c.serial for c in self.classrooms ])
        classrooms_to_delete = set([ c.serial for c in self.classrooms ]) - set(classrooms_serial_list)
        for serial in classrooms_to_add:
            TopicClassroom(topic=self, classroom=Classroom.objects.get(serial=serial)).save()
        for serial in classrooms_to_delete:
            TopicClassroom.objects.get(topic=self, classroom=Classroom.objects.get(serial=serial)).delete()

    def _get_antes(self):
        return list({ td.ante for td in TopicDependency.objects.filter(post=self) })

    def _get_classrooms(self):
        return list({ tc.classroom for tc in TopicClassroom.objects.filter(topic=self) })

    def _get_posts(self):
        return list({ td.post for td in TopicDependency.objects.filter(ante=self) })

    def _get_questions(self):
        return list(Question.objects.filter(topic=self))

    antes = property(_get_antes)
    classrooms = property(_get_classrooms)
    posts = property(_get_posts)
    questions = property(_get_questions)

class TopicDependency(models.Model):
    ante = models.ForeignKey('Topic', related_name='topicdependency_ante')
    post = models.ForeignKey('Topic', related_name='topicdependency_post')

    def __str__(self):
        return "%s BEFORE %s" % (self.ante, self.post)

class TopicClassroom(models.Model):
    topic = models.ForeignKey(Topic, related_name='topicclassroom_topic')
    classroom = models.ForeignKey(Classroom, related_name='topicclassroom_classroom')

    def __str__(self):
        return "%s FOR %s" % (self.topic, self.classroom)

class Option(models.Model):
    question = models.ForeignKey('Question', related_name="option_question")
    text = models.TextField()
    status = models.CharField(max_length=1, choices=(   ('a', 'accepted'),
                                                        ('p', 'pending'),
                                                        ('r', 'rejected') ))
    user = models.ForeignKey(User, blank=True, null=True)
    submit_time = models.DateTimeField(auto_now_add=True)
    interval = models.DurationField(blank=True, null=True)

    def __str__(self):
        return "%s %s: %s TO %s (%s)" % (self.user.username, self.submit_time, self.text, self.question.pk, self.status)

class Question(models.Model):
    text = models.TextField()
    topic = models.ForeignKey('Topic', related_name='question_topic')
    kind = models.CharField(max_length=8, choices=( ('ibool', 'instant boolean'),
                                                    ('imulti', 'instant multiple'),
                                                    ('iopen', 'instant open'),
                                                    ('pbool', 'paperwork boolean'),
                                                    ('pmulti', 'paperwork multiple'),
                                                    ('popen', 'paperwork open'),
                                                    ('delay', 'delayed'),
                                                    ('eval', 'evaluation')))
    note = models.TextField(blank=True, null=True)

    def __str__(self):
        return "(T%s %s %s) %s" % (self.topic.pk, self.kind, self.pk, self.text[:80])

    def _get_options(self):
        return list(Option.objects.filter(question=self))

    def distinct_nonpending_options(self):
        return [ Option.objects.filter(question=self, text=text).first() for text in { option.text for option in Option.objects.filter(question=self) if option.status != 'p' } ]

    def get_correct(self):
        try:
            return Option.objects.filter(question=self, status='a').first()
        except:
            return None

    def get_uptofive(self):
        l =  [self.get_correct()] + [ Option.objects.filter(question=self, text=text).first() for text in { option.text for option in Option.objects.filter(question=self) if option.status == 'r' } ][:4]
        shuffle(l)
        return l

    def get_status(self, answer):
        equivalent_options = Option.objects.filter(question=self, text=answer)
        if len(equivalent_options)>0:
            if all( option.status == 'a' for option in equivalent_options ):
                status = 'a'
            elif all( option.status == 'r' for option in equivalent_options ):
                status = 'r'
            else:
                status = 'p'
        elif self.kind in ['ibool', 'imulti', 'iopen', 'pbool', 'pmulti', 'popen']:
            accepted_options = Option.objects.filter(question=self, status='a')
            if answer in [ option.text for option in accepted_options ]:
                status = 'a'
            else:
                status = 'r'
        else:
            status = 'p'
        return status

    def shuffled_options(self):
        l = self.distinct_nonpending_options()
        shuffle(l)
        return l

    options = property(_get_options)

class Score(models.Model):
    user = models.ForeignKey(User, related_name='score_user')

blooming/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.shortcuts import redirect, render
from random import choice
from content.models import *
from bloomerprofile.models import *
import logging
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import ensure_csrf_cookie

@never_cache
@ensure_csrf_cookie
def index(request):
  if request.user.is_authenticated():
    bloomer = Bloomer.objects.get(username=request.user.username)
    return render(request, 'blooming/index.html', {'bloomer':bloomer})
  else:
    return render(request, 'blooming/homepage.html')

def login_view(request):
    if request.user.is_authenticated():
        return redirect('blooming:index')
    if request.method == 'GET':
        return render(request, 'blooming/login.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            #messages.success(request, 'Benvenut@ %s' % username)
            messages.success(request, "C'è un nuovo bottone «RiFormula», serve per sistemare le formule se vengono fuori formattate male.")
            return redirect('blooming:index')
        else:
            messages.error(request, 'Accesso non effettuato. Ritenta o contatta il tuo insegnante.')
            return redirect('blooming:index')

@login_required
def profile(request):
    return render(request, 'blooming/profile.html', {'bloomer':Bloomer.objects.get(username=request.user.username)})

blooming/templates/blooming/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Applicazione do allenamento per la matematica">
    <meta name="author" content="Matteo Bortolotto">
    <!-- <link rel="icon" href="../../favicon.ico"> -->

    <title>Yamath</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <style type="text/css">
        body {
          padding-top: 70px;
          padding-bottom: 30px;
        }

        .theme-dropdown .dropdown-menu {
          position: static;
          display: block;
          margin-bottom: 20px;
        }

        .theme-showcase > p > .btn {
          margin: 5px 0;
        }

        .theme-showcase .navbar .container {
          width: auto;
        }
    </style>
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Yamath</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form form-inline my-2 my-lg-0 pull-right" method="post" action="{% url 'blooming:login' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" name="username" placeholder="Nome utente">
            <input class="form-control mr-sm-2" type="password" name="password" placeholder="Parola chiave">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Accedi</button>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      {% if messages %}
      <div class="row">
        <div class="col-xs-12">
          {% for message in messages %}
          {% if message.tags == 'error' %}
          <div class="alert alert-danger">{{ message }}</div>
          {% elif message.tags == 'success' %}
          <div class="alert alert-success">{{ message }}</p>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </div>

    <div class="container theme-showcase" role="main">
      <div class="jumbotron">
        <h1>Benvenut@ eternauta</h1>
        <p>Questa è una pagina di allenamento. Se hai un profilo, fatti riconoscere.</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'blooming:login' %}" role="button">Accedi &raquo;</a></p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  </body>
</html>

blooming/templates/blooming/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Applicazione do allenamento per la matematica">
    <meta name="author" content="Matteo Bortolotto">

    <title>Yamath</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({extensions: ["tex2jax.js"], jax: ["input/TeX", "output/HTML-CSS"], tex2jax: {inlineMath: [ ['$','$'], ["\\(","\\)"] ], displayMath: [ ['$$','$$'], ["\\[","\\]"] ], processEscapes: true }, "HTML-CSS": { availableFonts: ["TeX"] } }); </script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <style type="text/css">
        body {
          padding-top: 70px;
          padding-bottom: 30px;
        }

        .theme-dropdown .dropdown-menu {
          position: static;
          display: block;
          margin-bottom: 20px;
        }

        .theme-showcase > p > .btn {
          margin: 5px 0;
        }

        .theme-showcase .navbar .container {
          width: auto;
        }
    </style>
    <script type="text/javascript" src="{% static 'js/personal.js' %}"></script>
    <script type="text/javascript">
      // using jQuery
      function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = jQuery.trim(cookies[i]);
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getCookie('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
      localStorage['bloomerUsername'] = '{{ bloomer.username }}';
      localStorage['serieSerial']='none';
      localStorage['topicSerial']='none';
      localStorage['questionSerial']='none';
      localStorage['answer']='none';
      loadDoneSeries('{{ bloomer.username}}');
      loadTodoSeries('{{ bloomer.username}}');
      loadLateSeries('{{ bloomer.username}}');
      loadEnvelopes('{{ bloomer.username}}');
    </script>
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle"  onClick="window.location.assign('{% url 'logout' %}');">
            <span class="glyphicon glyphicon-log-out" style="color:#ddd;"></span>
          </button>
          <button type="button" class="navbar-toggle" onClick="sendEnvelope();">
            <span class="glyphicon glyphicon-envelope" style="color:#ddd;"></span>
          </button>
          <button type="button" class="navbar-toggle" onClick="window.location.assign('{% url 'blooming:index' %}');">
            <span class="glyphicon glyphicon-book" style="color:#ddd;"></span>
          </button>
          <button type="button" class="navbar-toggle" onClick="window.location.assign('{% url 'backend:bloomer_details' bloomer.username %}');">
            <span class="glyphicon glyphicon-user" style="color:#ddd;"></span>
          </button>
          <button type="button" class="navbar-toggle" onClick="mathjaxTypeset();">
            <span class="glyphicon glyphicon-refresh" style="color:#ddd;"></span>
          </button>
          <a class="navbar-brand" href="/">Yamath</a>
        </div>
        <div id="navbar0" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <div class="navbar-form form-inline" method="get" action="#" autocomplete="off">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" onClick="MathJax.Hub.Queue(['Typeset',MathJax.Hub]);">
                  RiFormula <span class="glyphicon glyphicon-refresh"></span>
                </button>
              </div>
            </li>
            <li>
              <form class="navbar-form form-inline" method="get" action="{% url 'backend:bloomer_details' bloomer.username %}" autocomplete="off">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                  Profilo <span class="glyphicon glyphicon-user"></span>
                </button>
              </form>
            </li>
            <li>
              <form class="navbar-form form-inline" method="get" action="{% url 'blooming:index' %}" autocomplete="off">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                  Contenuti <span class="glyphicon glyphicon-book"></span>
                </button>
              </form>
            </li>
            <li>
              <div class="navbar-form form-inline" method="post" action="#" autocomplete="off">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"  onClick="sendEnvelope();">
                  Messaggio <span class="glyphicon glyphicon-envelope"></span>
                </button>
              </div>
            </li>
            <li>
              <form class="navbar-form form-inline" method="post" action="{% url 'logout' %}" autocomplete="off">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                  Esci <span class="glyphicon glyphicon-log-out"></span>
                </button>
              </form>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% if request.user.is_superuser %}
    <p><a href="{% url 'backend:index' %}">Backend</a></p>
    {% endif %}
    <div class="container" id="messageDisplay">
      {% if messages %}
      <div class="row" id="messageDisplayDjango">
        <div class="col-xs-12">
          {% for message in messages %}
          {% if message.tags == 'error' %}
          <p class="alert alert-danger">{{ message }}</p>
          {% elif message.tags == 'success' %}
          <p class="alert alert-success">{{ message }}</p>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-xs-12">
          <div class="alert alert-danger" id="messageDisplayError" style="display: none;"></div>
          <div class="alert alert-success" id="messageDisplaySuccess" style="display: none;"></div>
        </div>
      </div>
    </div>
    
    <div class="container theme-showcase" role="main">
      <div id="seriesIndex">
        <h3>Argomenti completati</h3>
        <ol id='doneSeries'></ol>
        <h3>Argomenti da affrontare</h3>
        <ol id='todoSeries'></ol>
        <h3>Argomenti per il futuro</h3>
        <ol id='lateSeries'></ol>
        <h3>Messaggi per te</h3>
        <ol id='envelopes'></ol>
      </div>
      <div id="questionDisplay">
        <div class="container">
          <div class="row" id='questionDisplayText'>
          </div>
          <div class="row" id='questionDisplayForm'>
          </div>
        </div>
      </div>
    </div>
  <p>Se vuoi, visita la pagina sperimentale della <a href="{% url 'look:main' %}">nuova versione</a>.</p>
  </body>
</html>