backend/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^bloomers/', views.bloomers, name="bloomers"),
    url(r'^bloomer_details/(?P<username>[0-9A-Za-z]+)/$', views.bloomer_details, name="bloomer_details"),
    url(r'^classrooms/', views.classrooms, name="classrooms"),
    url(r'^classroom_details/(?P<name>[0-9A-Za-z]+)/$', views.classroom_details, name="classroom_details"),
    url(r'^envelopes/', views.envelopes, name='envelopes'),
    url(r'^sendEnvelope/', views.sendEnvelope, name="sendEnvelope"),
    url(r'^series/', views.series, name="series"),
    url(r'^serie_details/(?P<serieSerial>[0-9A-Za-z]+)/$', views.serie_details, name="serie_details"),
    url(r'^serie_new/', views.serie_new, name="serie_new"),
    url(r'^topic_details/(?P<topicSerial>[0-9A-Za-z]+)/$', views.topic_details, name="topic_details"),
    url(r'^topic_new/(?P<serieSerial>[0-9A-Za-z]+)/$', views.topic_new, name="topic_new"),
    url(r'^question_details/(?P<questionSerial>[0-9A-Za-z]+)/$', views.question_details, name="question_details"),
    url(r'^question_new/(?P<topicSerial>[0-9A-Za-z]+)/$', views.question_new, name="question_new"),
    url(r'^option_details/(?P<optionSerial>[0-9A-Za-z]+)/$', views.option_details, name="option_details"),
    url(r'^option_new/(?P<questionSerial>[0-9A-Za-z]+)/$', views.option_new, name="option_new"),
    url(r'^copy/(?P<oldSerial>[0-9A-Za-z]+)-(?P<newSerial>[0-9A-Za-z]+)/$', views.copy, name="copy"),
    url(r'^delete/(?P<serial>[0-9A-Za-z]+)/$', views.delete, name="delete"),
    ###
    url(r'^claim/$', views.claim, name="claim"),
    url(r'^claim_solved/(?P<claim_pk>[0-9A-Za-z]+)/$', views.claim_solved, name="claim_solved"),
    url(r'^claims/$', views.claims, name="claims"),
    url(r'^create_bulk_bool/$', views.create_bulk_bool, name="create_bulk_bool"),
    url(r'^create_multi/$', views.create_multi, name="create_multi"),
    url(r'^create_topic/$', views.create_topic, name="create_topic"),
    url(r'^new_question/', views.new_question, name="new_question"),
    url(r'^pendings/', views.pendings, name="pendings"),
    url(r'^pending_details/(?P<option_pk>[0-9A-Za-z]+)/', views.pending_details, name="pending_details"),
    url(r'^pending_solved/(?P<option_pk>[0-9A-Za-z]+)/', views.pending_solved, name="pending_solved"),
    ###
    #url(r'^topic_questions/(?P<topic_serial>[0-9A-Z]+)/$', views.topic_questions, name="topic_questions"),
    #url(r'^tools/add_questionmultiple/$', views.tools_add_questionmultiple, name="tools_add_questionmultiple"),
]

look/urls.py
from django.conf.urls import url

from . import views
from back import views as back_views

urlpatterns = [
    url(r'^$', views.main, name="main"),
    url(r'^html/$', views.html, name="html"),
    url(r'^back/$', back_views.back, name="back"),
]

yamath/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blooming.views import index, login_view

urlpatterns = [
    url(r'^$', index, name='main'),
    url(r'^login/$', login_view),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^bloomerprofile/', include('bloomerprofile.urls', namespace='bloomerprofile')),
    url(r'^backend/', include('backend.urls', namespace='backend')),
    url(r'^blooming/', include('blooming.urls', namespace='blooming')),
    url(r'^experimental/', include('look.urls', namespace='look')),
]

backend/models.py
from django.db import models
import blooming.models as blooming
#import content.models as content
#import bloomerprofile.models as bloomerprofile
# from django.core.serializers.json import DjangoJSONEncoder

# class LazyEncoder(DjangoJSONEncoder):
#     def default(self, obj):
#         if isinstance(obj, bloomerprofile.Serie):
#             return force_text(obj)
#         return super(LazyEncoder, self).default(obj)

class Claim(models.Model):
    bloomer = models.ForeignKey(blooming.Bloomer, related_name='claim_bloomer', blank=True, null=True)
    topic = models.ForeignKey(blooming.Topic, related_name='claim_topic', blank=True, null=True)
    question = models.ForeignKey(blooming.Question, related_name='claim_question', blank=True, null=True)
    option = models.ForeignKey(blooming.Option, related_name='claim_option', blank=True, null=True)
    text = models.TextField(blank=True, null=True)

backend/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from django.views.decorators.cache import never_cache
from bloomerprofile.models import *
from content.models import *
import backend.models as backend
from django.contrib import messages
from backend.create_views import *
from django.contrib.auth import authenticate, login

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def index(request):
    bloomers = sorted(Bloomer.objects.all(), key=(lambda bloomer: bloomer.mean))
    classrooms = Classroom.objects.all()
    series = Serie.objects.all()
    return render(request, 'backend/index.html', {'bloomers':bloomers, 'classrooms':classrooms, 'series':series})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def bloomers(request):
    return render(request, 'backend/bloomers.html', {'bloomers':Bloomer.objects.all(), 'classrooms':Classroom.objects.all()})

@never_cache
def bloomer_details(request, username):
    if not (request.user.is_superuser or request.user.username == username):
        return redirect('/')
    bloomer = Bloomer.objects.get(username=username)
    classrooms = Classroom.objects.all()
    if request.method == 'GET':
        return render(request, 'backend/bloomer_details.html', {'bloomer':bloomer, 'classrooms':classrooms})
    elif request.method == 'POST':
        bloomer.first_name = request.POST['first_name']
        bloomer.last_name = request.POST['last_name']
        bloomer.email = request.POST['email']
        if 'password' in request.POST and len(request.POST['password'])>4:
            bloomer.set_password(request.POST['password'])
        bloomer.save()
        return render(request, 'backend/bloomer_details.html', {'bloomer':bloomer, 'classrooms':classrooms})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def classrooms(request):
    return render(request, 'backend/classrooms.html', {'classrooms':Classroom.objects.all()})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def classroom_details(request, name):
    classroom = Classroom.objects.get(name=name)
    if request.method == 'GET':
        return render(request, 'backend/classroom_details.html', {'classroom':classroom})
    elif request.method == 'POST':
        classroom.name = request.POST['name']
        if request.POST['add_serie']:
            classroom.add_serie(Serie.objects.get(serial=request.POST['add_serie']))
        if request.POST['add_bloomer']:
            classroom.add_bloomer(Bloomer.objects.get(username=request.POST['add_bloomer']))
        if request.POST['del_serie']:
            classroom.del_serie(Serie.objects.get(serial=request.POST['del_serie']))
        if request.POST['del_bloomer']:
            classroom.del_bloomer(Bloomer.objects.get(username=request.POST['del_bloomer']))
        classroom.save()
        return render(request, 'backend/classroom_details.html', {'classroom':classroom})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def copy(request, oldSerial, newSerial):
    if len(oldSerial)==3 and len(newSerial)==3:
        oldSerie = Serie.objects.get(serial=oldSerial)
        newSerie = Serie(serial=newSerial, name=oldSerie.name, recollection=oldSerie.recollection)
        newSerie.save()
        for ante in oldSerie.antes:
            newSerie.add_ante(ante)
        for oldTopic in oldSerie.topics:
            copy(request, oldTopic.serial, newSerial+oldTopic.serial[3:])
    elif len(oldSerial)==6 and len(newSerial)==6:
        oldTopic = Topic.objects.get(serial=oldSerial)
        newSerie = Serie.objects.get(serial=newSerial[0:3])
        newTopic = Topic(serial=newSerial, kind=oldTopic.kind, mobile=oldTopic.mobile, name=oldTopic.name, serie=newSerie)
        newTopic.save()
        for oldQuestion in oldTopic.questions:
            copy(request, oldQuestion.serial, newSerial+oldQuestion.serial[6:])
    elif len(oldSerial)==9 and len(newSerial)==9:
        oldQuestion=Question.objects.get(serial=oldSerial)
        newTopic = Topic.objects.get(serial=newSerial[0:6])
        newQuestion = Question(serial=newSerial, text=oldQuestion.text, topic=newTopic, kind=oldQuestion.kind)
        newQuestion.save()
        for oldOption in oldQuestion.options:
            copy(request, oldOption.serial, newSerial+oldOption.serial[9:])
    elif len(oldSerial)==12 and len(newSerial)==12:
        oldOption = Option.objects.get(serial=oldSerial)
        newQuestion = Question.objects.get(serial=newSerial[0:9])
        newOption = Option(serial=newSerial, question=newQuestion, text=oldOption.text, accepted=oldOption.accepted)
        newOption.save()
    else:
        raise ValueError("Serials does not match")
    return redirect(reverse("backend:index"))



@never_cache
@user_passes_test(lambda u: u.is_superuser)
def delete(request, serial):
    if len(serial)==3:
        Serie.objects.get(serial=serial).delete()
    elif len(serial)==6:
        Topic.objects.get(serial=serial).delete()
    elif len(serial)==9:
        Question.objects.get(serial=serial).delete()
    elif len(serial)==12:
        Option.objects.get(serial=serial).delete()
    else:
        raise ValueError("Serial mismatch")
    return redirect(reverse("backend:index"))

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def envelopes(request):
    return render(request, 'backend/envelopes.html', {'envelopes':Envelope.objects.all()})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def sendEnvelope(request):
    if request.method == 'GET':
        bloomer = Bloomer.objects.get(username=request.user.username)
        return render(request, 'backend/sendEnvelope.html', {'bloomer':bloomer})
    elif request.method == 'POST':
        sender = Bloomer.objects.get(username=request.POST['senderUsername'])
        receiver = Bloomer.objects.get(username=request.POST['receiverUsername'])
        text = request.POST['text']
        Envelope.objects.create(sender=sender, receiver=receiver, text=text)
        return redirect(reverse('backend:envelopes'))

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def series(request):
    series = Serie.objects.all()
    return render(request, 'backend/series.html', {'series':series})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def serie_new(request):
    if request.method == 'GET':
        return render(request, 'backend/serie_new.html')
    elif request.method == 'POST':
        serie = Serie.objects.create(serial='0', name='N/N')
        serie.name = request.POST['name']
        serials = { int(s.serial) for s in Serie.objects.all() }
        serie.serial = "{0:03d}".format(min( set(range(1, max(serials)+2)) - serials ))
        serie.save()
        return redirect(reverse('backend:serie_details', args=(serie.serial,)))
        return render(request, 'backend/serie_details.html', {'serie':serie})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def serie_details(request, serieSerial):
    serie = Serie.objects.get(serial=serieSerial)
    if request.method == 'GET':
        return render(request, 'backend/serie_details.html', {'serie':serie})
    elif request.method == 'POST':
        serie.name = request.POST['name']
        if 'add_ante' in request.POST and len(request.POST['add_ante'])>0:
            serie.add_ante(request.POST['add_ante'])
        if 'del_ante' in request.POST and len(request.POST['del_ante'])>0:
            serie.del_ante(request.POST['del_ante'])
        serie.save()
        return render(request, 'backend/serie_details.html', {'serie':serie})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def topic_new(request, serieSerial):
    if request.method == 'GET':
        serie = Serie.objects.get(serial=serieSerial)
        serials = {0}.union({ int(t.serial[-3:]) for t in Topic.objects.filter(serie=serie) })
        serial = "{0}{1:03d}".format(serie.serial, min( set(range(1, max(serials)+2)) - serials ))
        topic = Topic.objects.create(serial=serial, name='name', serie=serie)
        topic.save()
        return redirect(reverse('backend:topic_details', args=(topic.serial,)))

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def topic_details(request, topicSerial):
    topic = Topic.objects.get(serial = topicSerial)
    if request.method == 'GET':
        return render(request, 'backend/topic_details.html', {'topic':topic})
    elif request.method == 'POST':
        topic.name = request.POST['name']
        topic.mobile = 'mobile' in request.POST
        try:
            topic.kind = int(request.POST['kind'])
        except:
            pass
        topic.save()
        return render(request, 'backend/topic_details.html', {'topic':topic})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def question_new(request, topicSerial):
    if request.method == 'GET':
        topic = Topic.objects.get(serial=topicSerial)
        serials = {0}.union({ int(q.serial[-3:]) for q in Question.objects.filter(topic=topic) })
        serial = "{0}{1:03d}".format(topic.serial, min( set(range(1, max(serials)+2)) - serials ))
        question = Question.objects.create(serial=serial, text='text', topic=topic, kind='o')
        question.save()
        return redirect(reverse('backend:question_details', args=(question.serial,)))

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def question_details(request, questionSerial):
    question = Question.objects.get(serial = questionSerial)
    if request.method == 'GET':
        return render(request, 'backend/question_details.html', {'question':question})
    elif request.method == 'POST':
        question.text = request.POST['text']
        question.kind = request.POST['kind']
        question.save()
        return render(request, 'backend/question_details.html', {'question':question})

@never_cache
@user_passes_test(lambda u: u.is_superuser)
def option_new(request, questionSerial):
    if request.method == 'GET':

backend/templates/backend/bloomer_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Bloomer: {{ bloomer.user.username }}</h1>
<p>Username: {{ bloomer.user.username }} {% if bloomer.professor %} is professor {% endif %}</p>
<p>First_name: {{ bloomer.first_name }}</p>
<p>Last_name: {{ bloomer.last_name }}</p>
<p>Email: {{ bloomer.email }}</p>
<p>Classrooms: {% for classroom in bloomer.classrooms %}<a href="{% url 'backend:classroom_details' classroom.serial %}">{{ classroom.serial }}</a>, {% endfor %}</p>
<hr />
<form method="post" action="{% url 'backend:bloomer_details' bloomer.user.username %}" autocomplete="off">
{% csrf_token %}
<table>
<p>First_name: <input type="text" name="first_name" value="{{ bloomer.first_name }}" /></p>
<p>Last_name: <input type="text" name="last_name" value="{{ bloomer.last_name }}" /></p>
<p>Email: <input type="text" name="email" value="{{ bloomer.email }}" /></p>
<p>Is professor: <input type="checkbox" name="professor" {% if bloomer.professor %}checked{% endif %} /></p>
<ol>
    {% for classroom in classrooms %}
    <li>
        <input type="checkbox" name="classroom_checkbox_{{ classroom.serial }}" {% if classroom in bloomer.classrooms %}checked{% endif %} /> {{ classroom.serial }}
    </li>
    {% endfor %}
</ol>
<input type="submit" value="salva" />
</form>

{% endblock %}

backend/templates/backend/bloomer_details.html
{% extends "base.html" %}
{% load backend_extras %}

{% block content %}

<form method="post" action="{% url 'backend:bloomer_details' bloomer.username %}" autocomplete="off">
{% csrf_token %}
<h1>Profile: {{ bloomer.username }}</h1>
<p>Nome: <input type="text" name="first_name" value="{{ bloomer.first_name }}" /></p>
<p>Cognome: <input type="text" name="last_name" value="{{ bloomer.last_name }}" /></p>
<p>Email: <input type="text" name="email" value="{{ bloomer.email }}" /></p>
<p>Nuova password [almeno quattro caratteri (<strong>attenzione!</strong>)]: <input type="text" name="password" value="" /></p>
<p>Classe: {% for c in bloomer.classrooms %}{{ c.name }}, {% endfor %}</p>
<input type="submit" value="salva" />
</form>
<a href="{% url 'main' %}">Torna alla pagina principale</a>
<h2>Punteggi</h2>
{% for s in bloomer.series %}
<h3>{{ s.name }} ({{ bloomer|bsMean:s|stringformat:"0.2f" }})</h3>
{% for t in s.topics %}
<p> - {{ t.name }} ({{ bloomer|btMean:t|stringformat:"0.2f" }})</p>
{% endfor %}
{% endfor %}

{% endblock %}

backend/templates/backend/classroom_details.html
{% extends "base.html" %}

{% block content %}


<form method="post" action="{% url 'backend:classroom_details' classroom.name %}" autocomplete="off">
{% csrf_token %}
<p><a href="{% url 'backend:index' %}">backend</a> / <a href="{% url 'backend:classrooms' %}">classrooms</a></p>
<h1>Classroom: {{ classroom.name }}</h1>
<p>Name <input type="text" name="name" value="{{ classroom.name }}" /></p>
<p>
    Series
    <ol>
        {% for serie in classroom.series %}
        <li>
            {{ serie.serial }} <a href="{% url 'backend:serie_details' serie.serial %}">{{ serie.name }}</a>
        </li>
        {% endfor %}
        <li>
            add serie <input type="text" name="add_serie" />
        </li>
        <li>
            del serie <input type="text" name="del_serie" />
        </li>
    </ol>
</p>
<p>
    Bloomers
    <ol>
    {% for bloomer in classroom.bloomers %}
        <li>
            <a href="{% url 'backend:bloomer_details' bloomer.username %}">{{ bloomer.username }}</a>
        </li>
    {% endfor %}
        <li>
            add bloomer <input type="text" name="add_bloomer" />
        </li>
        <li>
            del bloomer <input type="text" name="del_bloomer" />
        </li>
    </ol>
</p>
<input type="submit" value="salva" />
</form>

{% endblock %}

backend/templates/backend/classrooms.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url 'backend:index' %}">backend</a></p>
<h1>Classrooms</h1>
<p>
    <ol>
    {% for classroom in classrooms %}
        <li>Classroom <a href="{% url 'backend:classroom_details' classroom.name %}">{{ classroom.name }}</a></li>
    {% endfor %}
    </ol>
</p>

{% endblock %}

backend/templates/backend/create_bulk_bool.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="post" action="{% url 'backend:create_bulk_bool' %}" autocomplete="off">
    {% csrf_token %}
    <div class="row">
        <div class="col-xs-12 header text-left"><h1>Create bulk bool</h1></div>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <p>Topic <input type="text" name="topic_pk" value="" /></p>
        </div>
        <div class="col-xs-4">
            <p>Kind <input type="text" name="kind" value="" /></p>
        </div>
    </div>
    {% for i in "0123456789"|make_list %}
    <div class="row">
        <div class="col-xs-1">
            <p>Vero? <input type="checkbox" name="checkbox_{{ i }}" /></p>
        </div>
        <div class="col-xs-11">
            <textarea name="text_{{ i }}" style="width:100%; height:30px;"></textarea></p>
        </div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-xs-12">
            <input type="submit" value="salva" style="width:100%;">
        </div>
    </div>
    </form>
</div>
<!--
<p>Topic</p>
<p>Text: {{ topic.text }} </p>
<p>Bloom: {{ topic.bloom_index }} {% if topic.mobile %}mobile{% endif %}</p>
<p>Antes: {% for ante in topic.antes %}<a href="{% url 'backend:topic_details' ante.pk %}">{{ ante.pk }}</a>, {% endfor %}</p>
<p>Posts: {% for post in topic.posts %}<a href="{% url 'backend:topic_details' post.pk %}">{{ post.pk }}</a>, {% endfor %}</p>
<p>Classrooms: {% for classroom in topic.classrooms %}<a href="{% url 'backend:classroom_details' classroom.serial %}">{{ classroom.serial }}</a>, {% endfor %}</p>
<hr />
<form method="post" action="% url 'backend:topic_details' topic.pk %}" autocomplete="off">
{% csrf_token %}
<p>Text: <input type="text" name="text" value="{{ topic.text }}" /></p><hr />
<p>Bloom: <input type="text" name="bloom_index" value="{{ topic.bloom_index }}" /> mobile <input type="checkbox" name="mobile" {% if topic.mobile %}checked{% endif %}</p><hr />
<p>Antes: add one<input type="text" name="new_ante" value="" />
<ol>
    {% for ante in topic.antes %}
    <li>
        <input type="checkbox" name="antes_checkbox_{{ ante.pk }}" checked/> {{ ante.pk }}
    </li>
    {% endfor %}
</ol></p><hr />
<p>Posts: add one<input type="text" name="new_post"/>
<ol>
    {% for post in topic.posts %}
    <li>
        <input type="checkbox" name="posts_checkbox_{{ post.pk }}" checked/> {{ post.pk }}
    </li>
    {% endfor %}
</ol></p><hr />
<p>Classrooms:<ol>
    {% for classroom in classrooms %}
    <li>
        <input type="checkbox" name="classroom_checkbox_{{ classroom.serial }}" {% if classroom in topic.classrooms %}checked{% endif %} /> {{ classroom.serial }}
    </li>
    {% endfor %}
</ol></p>
<input type="submit" value="salva" />
</form>
-->
{% endblock %}

backend/templates/backend/envelopes.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url 'backend:index' %}">backend</a></p>
<h1>Envelopes</h1>
{% for envelope in envelopes %}
<div>
    <p>From {{ envelope.sender.username }}</p>
    <p>To: {{ envelope.receiver.username }}</p>
    <p>About {{ envelope.serie.name }} : {{ envelope.topic.name }} : {{ envelope.question.serial }}</p>
    <p>{{ envelope.question.text|safe }}</p>
    <p>{{ envelope.text }}</p>
    <a href="{% url 'backend:sendEnvelope' %}">Rispondi</a>
    <hr />
</div>
{% empty %}
<p>No envelopes</p>
{% endfor %}

{% endblock %}

backend/templates/backend/index.html
{% extends "base.html" %}

{% block content %}

<h1>Porte aperte</h1>
<p><a href="{% url 'backend:bloomers' %}">Bloomers</a></p>
<p><a href="{% url 'backend:classrooms' %}">Classrooms</a></p>
<p><a href="{% url 'backend:envelopes' %}">Envelopes</a></p>
<p><a href="{% url 'backend:series' %}">Series</a></p>


{% endblock %}

backend/templates/backend/option_details.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url 'backend:index' %}">backend</a> / <a href="{% url 'backend:series' %}">series</a> / <a href="{% url 'backend:serie_details' option.question.topic.serie.serial %}">{{ option.question.topic.serie.serial }}</a> / <a href="{% url 'backend:topic_details' option.question.topic.serial %}">{{ option.question.topic.serial }}</a> / <a href="{% url 'backend:question_details' option.question.serial %}">{{ option.question.serial }}</a> </p>
<h1>Option {{ option.serial }}</h1>
<form method="post" action="{% url 'backend:option_details' option.serial %}" autocomplete="off">
{% csrf_token %}
    <p>Question {{ option.question.serial }} <blockquote>{{ option.question.text|safe }}</blockquote></p>
    <p>Text <input type="text" name="text" value="{{ option.text }}" /></p>
    <p>Accepted <input type="checkbox" name="accepted" {% if option.accepted %}checked{% endif %}/></p>
<input type="submit" value="salva">
</form>
{% endblock %}

backend/templates/backend/pendings.html
{% extends "base.html" %}

{% block content %}

<h1>Pendings</h1>

{% for option in pendings %}
<p>Bloomer: {{ option.bloomer.user.username }}</p>
<p>Question {{ option.question.pk }}:<br />
<quote>{{ option.question.text|safe }}</quote></p>
<p>Option {{ .option.pk }} {{ option.status }}: {{ option.text }} (correct is {{ option.question.get_correct.text }})</p>
<form method="post" action="{% url 'backend:pending_solved' option.pk %}" autocomplete="off">
{% csrf_token %}
<input type="submit" name="option_accepted" value="Accepted" />
<input type="submit" name="option_rejected" value="Rejected" />
</form>
<hr />
{% endfor %}


{% endblock %}

backend/templates/backend/serie_details.html
{% extends "base.html" %}
{% load backend_extras %}

{% block content %}


<p><a href="{% url 'backend:index' %}">backend</a> / <a href="{% url 'backend:series' %}">series</a></p>
<form method="post" action="{% url 'backend:serie_details' serie.serial %}" autocomplete="off">
{% csrf_token %}
<h1>Serie {{ serie.serial }}</h1>
<p>Name <input type="text" name="name" value="{{ serie.name }}" /></p>
<p>
    Antes 
    <ol>
        {% for ante in serie.antes %}
        <li>
            {{ ante.serial }} {{ ante.name }}
        </li>
        {% endfor %}
        <li>
            add one<input type="text" name="add_ante" value="" />
        </li>
        <li>
            del one <input type="text" name="del_ante" value="" />
        </li>
    </ol>
</p>
<p>Posts: {{ serie.posts }}</p>
<p>Classrooms: {{ serie|getClassroomsOfSerie }}</p>
<p>
    Topics
    <ol>
    {% for topic in serie.topics %}
        <li>
            {{ topic.serial }} <a href="{% url 'backend:topic_details' topic.serial %}">{{ topic.name }}</a>
        </li>
    {% endfor %}
        <li>
            <a href="{% url 'backend:topic_new' serie.serial %}">new topic</a>
        </li>
    </ol>
</p>
<input type="submit" value="salva" />
</form>

{% endblock %}

backend/templates/backend/topic_details.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url 'backend:index' %}">backend</a> / <a href="{% url 'backend:series' %}">series</a> / <a href="{% url 'backend:serie_details' topic.serie.serial %}">{{ topic.serie.serial }}</a> </p>
<form method="post" action="{% url 'backend:topic_details' topic.serial %}" autocomplete="off">
{% csrf_token %}
<h1>Topic {{ topic.serial }}</h1>
<p>Name <input type="text" name="name" value="{{ topic.name }}" /></p>
<p>Serie {{ topic.serie.serial }} {{ topic.serie.name }}</p>
<p>Kind <input type="text" name="kind" value="{{ topic.kind }}" /></p>
<p>Mobile <input type="checkbox" name="mobile" {% if topic.mobile %}checked{% endif %}/></p>
<p>
    Questions
    <ol>
    {% for question in topic.questions %}
        <li>
            {{ question.serial }} <a href="{% url 'backend:question_details' question.serial %}">{{ question.text }}</a>
        </li>
    {% endfor %}
        <li>
            <a href="{% url 'backend:question_new' topic.serial %}">new question</a>
        </li>
    </ol>
</p>
<input type="submit" value="salva" />
</form>

{% endblock %}